export const DataTemp = [

 
  {
    des_art: "SET MARC SHARPIE  CAJA X23PCS",
    uni_med: "",
    num_art: "53239",
    cod_fab: "071641171282",
    cod_alt: "2087391",
    stock: 0,
    id_rubros: 27,
    id_lineas: 61,
    id_proveedor: 71020,
    id_articulo: 87208,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "AA. SIN MARCA",
    nomsub: "MARC.AL AGUA/ PERMAN. /P.PIZAR",
    cuerpo: "",
    estante: "",
    id_subrubros: 106,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "NEWELL BRANDS DE ARGENTINA SA",
    pre_art: 1872.23,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "S",
    web: "S",
    lis_pre: "S",
    canbul: 6,
    dto_art: 3,
    fec_pre: "30-May-22",
    pre_tmp: 0,
    pre_ant: 1872.23,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "ECOLAPIZ X12 CORTOS HEXAG FABER",
    uni_med: "",
    num_art: "39660",
    cod_fab: "7891360638681",
    cod_alt: "212011",
    stock: -31,
    id_rubros: 27,
    id_lineas: 39,
    id_proveedor: 10025,
    id_articulo: 76356,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "AW.FABER CASTELL",
    nomsub: "LAPICES - CRAYONES",
    cuerpo: "",
    estante: "",
    id_subrubros: 105,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "A.W. FABER CASTELL ARGENTINA S.A.",
    pre_art: 60.01,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "N",
    canbul: 0,
    dto_art: 0,
    fec_pre: "31-May-22",
    pre_tmp: 0,
    pre_ant: 60.01,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "LAPIZ MODELO SURTIDO",
    uni_med: "",
    num_art: "59794",
    cod_fab: "5993102213742",
    cod_alt: "21374",
    stock: 66,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 92923,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "LAPICES - CRAYONES",
    cuerpo: "",
    estante: "",
    id_subrubros: 105,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 27.09,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 36,
    dto_art: 0,
    fec_pre: "31-May-22",
    pre_tmp: 0,
    pre_ant: 27.09,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO CON BASE BOLSA",
    uni_med: "",
    num_art: "59311",
    cod_fab: "5993102213964",
    cod_alt: "21396",
    stock: 2,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 92519,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 296.1,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 12,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 296.1,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO ORO ROJO C/ STRASS ESTUCHE",
    uni_med: "",
    num_art: "59824",
    cod_fab: "5993102214312",
    cod_alt: "21431NA",
    stock: 31,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 92952,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 472.5,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 36,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 472.5,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "LAPIZ PUNTA CAMBIABLE DIAMANTE",
    uni_med: "",
    num_art: "59791",
    cod_fab: "5993102214374",
    cod_alt: "21437",
    stock: -10,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 92920,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "LAPICES - CRAYONES",
    cuerpo: "",
    estante: "",
    id_subrubros: 105,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 55.44,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 96,
    dto_art: 0,
    fec_pre: "31-May-22",
    pre_tmp: 0,
    pre_ant: 55.44,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO SILICONA PASTEL FLORES",
    uni_med: "",
    num_art: "59788",
    cod_fab: "5993102214411",
    cod_alt: "21441NA",
    stock: 2,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 92917,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 78.75,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 144,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 78.75,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "LAPICES X6 MICKEY Y MINNIE MOOVING",
    uni_med: "",
    num_art: "59464",
    cod_fab: "7798356618361",
    cod_alt: "2162160206",
    stock: -17,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 71078,
    id_articulo: 92644,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "LAPICES - CRAYONES",
    cuerpo: "",
    estante: "",
    id_subrubros: 105,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "MOOVING S.R.L.",
    pre_art: 236.15,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 120,
    dto_art: 0,
    fec_pre: "29-Jun-22",
    pre_tmp: 0,
    pre_ant: 205.35,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO PALTA",
    uni_med: "",
    num_art: "61659",
    cod_fab: "0000000061658",
    cod_alt: "21710",
    stock: 0,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94704,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 87.57,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 48,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO OSO C/GOMA",
    uni_med: "",
    num_art: "61660",
    cod_fab: "0000000061660",
    cod_alt: "21711",
    stock: -2,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94705,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 87.57,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 48,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO CONEJO X1",
    uni_med: "",
    num_art: "61658",
    cod_fab: "0000000061658",
    cod_alt: "21712",
    stock: -7,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94703,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 87.57,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 48,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO CONEJO C/GOMA",
    uni_med: "",
    num_art: "61661",
    cod_fab: "0000000061661",
    cod_alt: "21714",
    stock: -10,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94706,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 87.57,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 48,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIG TINTA AZUL BORRABLE ANIMAL",
    uni_med: "",
    num_art: "61178",
    cod_fab: "6956903284440",
    cod_alt: "21730NA",
    stock: 4,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94248,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 81.9,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 12,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO COLOR",
    uni_med: "",
    num_art: "61648",
    cod_fab: "6930126702226",
    cod_alt: "21795",
    stock: 3,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94693,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 74.97,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 240,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO DINOSAURIO",
    uni_med: "",
    num_art: "61650",
    cod_fab: "6972800190035",
    cod_alt: "21834",
    stock: 1,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94695,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 189,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 144,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO MULTI 6 COLORES  PALTA",
    uni_med: "",
    num_art: "62218",
    cod_fab: "6971886891232",
    cod_alt: "21838",
    stock: 1,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 95236,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 236.25,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 36,
    dto_art: 0,
    fec_pre: "23-Mar-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLOGRAFO C/LUZ Y GEL",
    uni_med: "",
    num_art: "61649",
    cod_fab: "6972898936027",
    cod_alt: "21839",
    stock: 2,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94694,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 252,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 144,
    dto_art: 0,
    fec_pre: "23-Mar-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO CON LIQUIDO GLITTER UNICORNIO",
    uni_med: "",
    num_art: "62260",
    cod_fab: "6972800190011",
    cod_alt: "21852",
    stock: 91,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 95275,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 196.88,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 36,
    dto_art: 0,
    fec_pre: "04-Jul-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO MULTI 3 COLORES FUTBOL",
    uni_med: "",
    num_art: "56990",
    cod_fab: "8512126884546",
    cod_alt: "21854",
    stock: 68,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 90517,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 181.13,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 36,
    dto_art: 0,
    fec_pre: "31-Mar-22",
    pre_tmp: 0,
    pre_ant: 113.67,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO DINOSAURIO C/luz",
    uni_med: "",
    num_art: "61651",
    cod_fab: "6756254182392",
    cod_alt: "21896NA",
    stock: 59,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94696,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 244.13,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 144,
    dto_art: 0,
    fec_pre: "31-Mar-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO PASTEL CON CLIP METAL",
    uni_med: "",
    num_art: "62262",
    cod_fab: "0000000062262",
    cod_alt: "21900NA",
    stock: 55,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 95277,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 118.13,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 24,
    dto_art: 0,
    fec_pre: "31-Mar-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "BOLIGRAFO 10 FUNCIONES FOTBOL",
    uni_med: "",
    num_art: "61652",
    cod_fab: "0000000061652",
    cod_alt: "21937",
    stock: 1,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94697,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 283.5,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 144,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "SELLOS DINO  X1",
    uni_med: "",
    num_art: "61663",
    cod_fab: "0000000061663",
    cod_alt: "21973",
    stock: -787,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 94708,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "BOLIG.-LAPICERAS- PORTAMINAS-M",
    cuerpo: "",
    estante: "",
    id_subrubros: 76,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 49.77,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "S",
    lis_pre: "S",
    canbul: 144,
    dto_art: 0,
    fec_pre: "26-Jan-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
  {
    des_art: "LAPIZ CON GOMA VIAJE ESTELAR",
    uni_med: "",
    num_art: "62261",
    cod_fab: "5993102223604",
    cod_alt: "22360NA",
    stock: -13,
    id_rubros: 27,
    id_lineas: 1,
    id_proveedor: 70747,
    id_articulo: 95276,
    nom_rub: "LIBRERIA ART. DE ESCRITURA",
    des_lin: "..SIN ASIGNAR",
    nomsub: "LAPICES - CRAYONES",
    cuerpo: "",
    estante: "",
    id_subrubros: 105,
    sto_min: 0,
    sto_opt: 0,
    razsoc: "COLOURS S.A.",
    pre_art: 68.67,
    stock02: 0,
    marca: 0,
    pre_may: 0,
    pre_art_ori: 0,
    pre_prov: 0,
    pre_prov_ori: 0,
    ofe_uno: 0,
    ofe_cin: 0,
    discontinuado: "N",
    web: "N",
    lis_pre: "S",
    canbul: 24,
    dto_art: 0,
    fec_pre: "31-May-22",
    pre_tmp: 0,
    pre_ant: 0,
    coeficiente: 0,
    lugar: "D",
  },
];



export const Rubros = [
  [
    { id: 1, 
      ESCRITURA: "ESCRITURA", 
      "MARCADORES Y RESALTADORES": "BOLIGRAFOS" },
    {
      id: 1,
      ESCRITURA: "ESCRITURA",
      "MARCADORES Y RESALTADORES": "MICROFIBRAS Y MARCADORES ESCOLARES",
    },
    {
      id: 1,
      ESCRITURA: "ESCRITURA",
      "MARCADORES Y RESALTADORES": "LAPICES DE COLORES Y CRAYONES",
    },
    {
      id: 1,
      ESCRITURA: "ESCRITURA",
      "MARCADORES Y RESALTADORES": "LAPICES GRAFITOS, PORTAMINAS Y MINAS",
    },
    { id: 2, ESCRITURA: "ESCOLAR", "MARCADORES Y RESALTADORES": "ADHESIVOS " },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "BRILLANTINA,LENTEJUELAS,LUPA,PALITOS",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "CARPETAS  ESCOLARES Y AROS DE CARPETA",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "CARTUCHERAS/CANOPLAS",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "CINTAS ADHESIVAS Y PORTAROLLO",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "GOMA, CORRECTOR , CINTA CORRECT.",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "LAMINAS EDUC./ TAB. PERIOD./DICCIONARIOS",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "MOCHILAS - BOLSOS",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "PIZARRAS, TABLEROS, TIZAS , BORRADORES",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "SACA / REGLA / COMPÁS/ESCUADRA/SET GEO",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "SEPARADORES, ETIQUETAS, ASIG., OJALILLOS",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "SET DE JARDIN  Y CANTIMPLORAS",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "TEMPERA, PLASTILINA,  ACUARELA Y PINCELES ",
    },
    {
      id: 2,
      ESCRITURA: "ESCOLAR",
      "MARCADORES Y RESALTADORES": "TIJERAS,CUTTERS, ETC",
    },
    {
      id: 3,
      ESCRITURA: "CUADERNOS Y REPUESTOS",
      "MARCADORES Y RESALTADORES": "CUADERNOS",
    },
    {
      id: 3,
      ESCRITURA: "CUADERNOS Y REPUESTOS",
      "MARCADORES Y RESALTADORES": "MAPAS Y LIBRETAS",
    },
    {
      id: 3,
      ESCRITURA: "CUADERNOS Y REPUESTOS",
      "MARCADORES Y RESALTADORES": "REPUESTOS",
    },
    {
      id: 3,
      ESCRITURA: "CUADERNOS Y REPUESTOS",
      "MARCADORES Y RESALTADORES": "BLOCK",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "MOLDE, MANTECA, MADERA Y MISIONERO",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "CARTONES, MICROCURRUGADO, BARRILETE",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "PAPEL DE FORRAR Y PAPEL GLASE",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "CELOFAN, ACETATO Y VARIO DE PVC",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "GOMA EVA",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "PAPEL CREPE,AFICHE,CARTULINAS, SEDA",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "CONTAC Y ROLLOS METALIZADOS",
    },
    {
      id: 4,
      ESCRITURA: "PAPELES, GOMA EVA Y PVC",
      "MARCADORES Y RESALTADORES": "RESMA Y PAPEL DE IMPRESIÓN",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "BIBLIORATO,CAJA ARCHIVERA",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "NOTAS AUTOADHESIVAS Y TACOS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "BANDAS ELASTICAS,CARBONICO Y TAL/NUMEROS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "PISTOLA DE ENCOLAR Y BARRAS DE SILICONA",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "ABROCHADORA, BROCHES ,SACABROCHES",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "BROCHES, ARANDELAS, NEPACOS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "CALCULADORAS Y ARTICULOS DE OFICINA",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "FICHAS Y FICHEROS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "CARPETAS COMERCIALES CART.ACRILICA.CLASI",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "TALONARIO,LIBRO COMERCIALE,COFRES Y ACC.",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "CLIP, APRIETA PAPEL,ALFILERE Y CHINCHES",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "TINTAS SELLO,TINTA MARCAD.,ALMOHADILLAS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "FOLIO,FUNDA,TAPAS,ESPIRALES,HILOS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "PERFORADORAS",
    },
    {
      id: 5,
      ESCRITURA: "COMERCIAL",
      "MARCADORES Y RESALTADORES": "SOBRES COMERCIALES",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "FLAUTAS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "PEGAMAMENTOS VARIO Y SILICONAS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "BOLSAS DE PAPEL",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "AGENDAS Y DIARIOS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "LIBROS COLOREAR Y CUENTOS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "ACRILICOS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "BASES ACRILICAS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "TIZA",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "DIMENSIONAL",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "BARNICES Y ACCESORIOS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "PINCELES ESPECIALES",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "PORCELANA FRIA Y ARCILLAS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "MOÑOS Y ETIQUETAS",
    },
    {
      id: 6,
      ESCRITURA: "ARTISTICA Y REGALERIA",
      "MARCADORES Y RESALTADORES": "PAPEL Y BOBINAS DE REGALO",
    },
  ],
];
